---
- hosts: localhost
  name: Setup Arch
  become: false
  tasks:
    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - neovim
          - firefox
          - arandr
          - kitty
          - lxappearance
          - transmission-cli
          - bat
          - ttf-fira-code
          - ttf-firacode-nerd
          - xclip
          - thunar
          - flameshot
          - redshift
          - graphviz
          - sd
          - ripgrep
          - duf
          - fd
          - git
          - base-devel
          - poetry
          - nushell
          - starship
          - xorg-xinit # provides startx
          - base-devel
          - fakeroot
        state: present

    - name: Symlink vim to nvim
      become: true
      ansible.builtin.file:
        src: /usr/bin/nvim
        dest: /usr/bin/vim
        owner: root
        group: root
        state: link

    - name: Symlink ~/.themes to ~/.config
      become: false
      ansible.builtin.file:
        src: ~/.config
        dest: ~/.themes
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        state: link

    - name: Set login shell of user {{ ansible_env.USER }} to `nu` with `usermod`
      ansible.builtin.command: usermod --shell /usr/bin/nu {{ ansible_env.USER }}
      become: true
      changed_when: false

    - name: Setup starship
      ansible.builtin.command: nu -c 'mkdir ~/.cache/starship; starship init nu | save -f ~/.cache/starship/init.nu'
      become: false
      changed_when: false

    - name: Create the ~/code directory
      become: false
      ansible.builtin.file:
        path: ~/code
        state: directory

    - name: Clone Paru
      become: false
      ansible.builtin.git:
        repo: https://aur.archlinux.org/paru.git
        dest: ~/code/paru
        version: master
      notify: Build Paru
    
    - name: Flush handlers
      meta: flush_handlers

  handlers:
    - name: Build Paru
      become: false
      ansible.builtin.command:
        chdir: ~/code/paru/
        cmd: makepkg -sri
