---
- hosts: localhost
  name: Setup Arch
  become: false
  tasks:
    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - alsa-utils # provides alsamixer
          - arandr
          - audacity
          - base-devel
          - base-devel
          - bat
          - bind # provides dig
          - btop
          - duf
          - entr
          - fakeroot
          - fd
          - feh
          - ffmpegthumbnailer
          - file-roller  # archive viewer
          - firefox
          - fish # for fish completions inside nushell
          - flameshot
          - fzf
          - gedit
          - git
          - gnu-netcat
          - graphviz
          - jq
          - less
          - lolcat
          - lxappearance
          - mediainfo
          - mpv
          - neofetch
          - neovim
          - npm # Required for pyright LSP
          - pavucontrol
          - poetry
          - redshift
          - ripgrep
          - rofi
          - rustup
          - sd
          - sl
          - sox
          - starship
          - thefuck
          - thunar
          - tldr
          - transmission-cli
          - ttf-fira-code
          - ttf-firacode-nerd
          - tumbler
          - vlc
          - wezterm
          - wget
          - xclip
          - xorg-xinit # provides startx
          - xorg-xkill
          - zathura
          - zathura-pdf-mupdf
          - zellij
          - zola
          - zoxide
        state: present

    - name: Symlink vim to nvim
      become: true
      ansible.builtin.file:
        src: /usr/bin/nvim
        dest: /usr/bin/vim
        owner: root
        group: root
        state: link

    - name: Symlink ~/.themes to ~/.config
      become: false
      ansible.builtin.file:
        src: ~/.config
        dest: ~/.themes
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        state: link

    - name: Set login shell of user {{ ansible_env.USER }} to `zsh` with `usermod`
      ansible.builtin.command: usermod --shell /usr/bin/zsh {{ ansible_env.USER }}
      become: true
      changed_when: false

    - name: Setup .zshrc
      ansible.builtin.copy:
        src: .zshrc
        dest: ~/.zshrc

    - name: Create the ~/code directory
      become: false
      ansible.builtin.file:
        path: ~/code
        state: directory

    - name: Clone Paru
      become: false
      ansible.builtin.git:
        repo: https://aur.archlinux.org/paru.git
        dest: ~/code/paru
        version: master
      notify: Build Paru
    
    - name: Flush handlers
      meta: flush_handlers

    - name: Ensure leftwm is installed
      become: false
      ansible.builtin.command: paru -S leftwm --noconfirm --needed
      changed_when: false

    - name: Run leftwm check
      become: false
      ansible.builtin.command: leftwm check
      changed_when: false

    - name: Ensure dragon-drop is installed
      become: false
      ansible.builtin.command: paru -S dragon-drop --noconfirm --needed
      changed_when: false

  handlers:
    - name: Build Paru
      become: false
      ansible.builtin.command:
        chdir: ~/code/paru/
        cmd: makepkg -sri
