# Don't print a new line at the start of the prompt
add_newline = false

# Which is equivalent to
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$rust\
$cmd_duration\
$custom\
$jobs\
$battery\
$time\
$status\
$character"""

