# Don't print a new line at the start of the prompt
add_newline = false


# Use custom format
format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$rust\
$nix_shell\
$memory_usage\
$env_var\
$cmd_duration\
$custom\
$jobs\
$time\
$status\
$character"""

[directory]
truncation_length = 8

[git_branch]
truncation_length = 35

[python]
disabled = false
style = "green bold"
scan_for_pyfiles = false

