[commands.swipe.three]
up = "xdotool key XF86MonBrightnessUp"
down = "xdotool key XF86MonBrightnessDown"
left = "xdotool key ctrl+alt+Left"
right = "xdotool key ctrl+alt+Right"

[commands.swipe.four]
up = "xdotool key XF86AudioRaiseVolume"
down = "xdotool key XF86AudioLowerVolume"
left = "playerctl previous"
right = "playerctl next"
