#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Apps autostart
picom &> /dev/null &
# betterlockscreen -l dimblur & 

# Set the theme.toml config
leftwm command "LoadTheme "$SCRIPTPATH"/theme.ron"

redshift 51.1:17.03 &

# Set background
feh --bg-fill ~/Pictures/wallpapers/vera.jpg &

