name: Test
on: [push]
jobs:
  provisionining:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ubuntu packages
        run: |
          sudo apt update
          docker run --name arch -d archlinux:latest sleep 3600
      - name: Setup ansible & dependencies
        run: |
          docker exec arch pacman -Syu ansible sudo --noconfirm
          docker exec arch bash -c "echo 'wint3rmute ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers"
      - name: Setup user
        run: |
          docker exec arch useradd -m wint3rmute
          docker cp $(pwd) arch:/home/wint3rmute/.config
          docker exec arch chown wint3rmute:wint3rmute /home/wint3rmute/.config
      - name: Run provisioning
        run: |
          docker exec -u wint3rmute -w /home/wint3rmute/.config arch ansible-playbook -v playbook.yml
